package.json
We need to identify type of license we use for the package on `package.json` file too.
=> fix(package): set license

.github/workflows/publish.yml, CONTRIBUTING.md
"Publish" workflow builds the package and deploys it to official npm registry.
Runs only on `release/*.*.x` branches, publishes only when a version is different from the one on the registry.
You can inspect [Actions](https://github.com/onfido/castor-icons/actions) to note that it is executed (test version without publishing) only on required branch: https://github.com/onfido/castor-icons/actions/runs/383365377
=> ci: publish package

package.json
This is just a suggestion, here's a preview:
It reads more poorly in `package.json`, but it reads better in the command line.
=> chore: make yarn warning easier to notice

.github/workflows/lint.yml
Dependabot sometimes [creates really long commits](https://github.com/onfido/castor-icons/pull/11) but that's not always bad.
Exclude running commitlint for Dependabot, to allow long commits.
On Dependabot MRs.
N/A
=> ci: commitlint exclude dependabot

CHANGELOG.md, CONTRIBUTING.md, package-lock.json, package.json
https://www.npmjs.com/package/@onfido/castor-icons/v/1.0.0
Merging version bump (and some other changes) back to the `main` branch.
=> chore: release 1.x.x

README.md
We're publishing package on npm registry but no easy way to know what's the latest version published.
Adding a badge to show the latest npm version published.
On the package description.
N/A
=> chore: npm version badge

.github/workflows/build.yml
Bad copy/paste - "build" job name accidently set as "publish".
Rename job to be "build".
N/A
N/A
=> ci: correct "build" job name

package.json
We're using ESLint that lints both TS and JS files, so naming script to `lint:es` is more appropriate.
Rename script `lint:ts` to `lint:es`.
Locally by running a script.
N/A
=> chore: rename lint:ts to lint:es

.github/workflows/preview.yml
As described on https://github.com/onfido/castor-icons/issues/53, we cannot use `pull_request_target` handler.
Temporary switch to only using `pull_request`, until switched to new preview provider.
Once PR merged.
N/A
=> ci: preview on pull request

README.md
React `Fragment` is not properly styled when on GitHub docs.
Instead of shorthand using full `<Fragment />` component. Also, showing inclusion of React itself in examples.
On GitHub itself.
N/A
=> docs: improve examples with react fragment

src/icons.json
"grid" icon will not be used.
Remove "grid" icon.
On preview.
BREAKING CHANGE: Use "grid-solid" instead of "grid" icon.
=> feat!: remove grid

.github/workflows/preview.yml, .github/workflows/publish.yml, CONTRIBUTING.md
Simplify release process.
Run 'publish' action on tags instead of branches, which makes the requirement for branches unimportant.
After merging with main, follow the new instructions in `CONTRIBUTING.md` and check `npm` for the new version.
1. I don't think we can protect tags in GitHub
2. Still requires branches for non-latest/diverging versions, e.g.
```
* chore(release): 2.0.1 (tag: v2.0.1)
* fix: foo
* chore(release): 2.0.0 (tag: v2.0.0)
* feat!: breaking change
|  * chore(release): 1.2.1 (tag: v1.2.1, release/1.x.x)
|  * fix: foo (tag: v1.2.1)
| /
* chore(release): 1.2.0 (tag: v1.2.0)
```
=> build: simplify release process

.svgrrc.json, README.md
Usually "fill" is needed as "currentColor" value, so better to have this set by default.
This closes https://github.com/onfido/castor-icons/issues/69.
Set "fill" to "currentColor" default on auto-generated React components, also enhance examples to also use such attribute as default.
On apps that use library, removing the default "fill" from usage.
N/A
=> feat: fill with "currentColor" by default

.github/workflows/deploy.yml
Icons list is deployed to GitHub Pages via [GitHub Actions](https://github.com/JamesIves/github-pages-deploy-action), however a commit history is kept for the branch that is not needed.
Use `SINGLE_COMMIT` as [described in an action used](https://github.com/JamesIves/github-pages-deploy-action#optional-choices) to force-push to a target branch, this will not keep a deployment history.
Only once this gets merged to `main`.
N/A
=> ci: deploy with single commit, don't keep history

CONTRIBUTING.md, package-lock.json, package.json
Switch to using [npm 7](https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/).
Change `package-lock.json` to new standard, require npm v7 and up to be used.
Locally, then on CI.
Node 14 came with npm 6 still, so people will need to upgrade locally in order to contribute to this package.
=> build: require (and use) npm 7

.github/workflows/deploy.yml, .github/workflows/preview.yml, .github/workflows/publish.yml, CONTRIBUTING.md
Allow branches like `release/1.0.1` to be able to publish too.
Rename `release/*.x.x` to `release/*` in all CI related files.
Check CI after merge when a new `release/*` branch is created.
None, already changed GitHub branch settings.
=> ci: rename release branches

.husky/.gitignore, .husky/commit-msg, .husky/pre-commit, .husky/prepare-commit-msg, .huskyrc.json, package-lock.json, package.json
Following [upgrade to Husky v5](https://github.com/onfido/castor-icons/pull/87) hooks no longer work.
Unable to use [automated upgrade script](https://github.com/typicode/husky-4-to-5), so instead switcking manually by following [migration gruide](https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v5).
Locally only.
N/A
=> build: fix husky v5 integration

.husky/.gitignore
Husky v5 integration [was fixed](https://github.com/onfido/castor-icons/pull/92) however `.gitignore` file was edited - Husky does not like this, as each time the file is force-generated.
Use default auto-generated `.gitignore` file.
`npm install` should not edit `.husky/.gitignore`.
Nothing apart annoyance :hurtrealbad:
=> build: use default .gitignore for husky

CHANGELOG.md
Duplicate changelog entries added with [v1.2.0 release](https://github.com/onfido/castor-icons/pull/60).
Remove duplicate entries.
On GitHub when merged.
This does not make a change to released versions (incl. tags), will only affect future releases.
=> docs: remove duplicate changelog entries

.github/workflows/lint.yml
Switch to using our own custom commands to run varioius linters.
We don't use features provided by the linting action, and also this creates problems with PRs made out of forks.
Don't use action, run individual custom commands on a workflow.
Once merged to the `main` branch.
N/A
=> ci: use custom lint commands

.github/workflows/lint.yml
Based on https://github.com/onfido/castor-icons/pull/142 we now use Dependabot Preview that has a different commit actor.
Change Dependabot actor from `dependabot` to `dependabot-preview`.
Only after merge - rebased [Dependabot PR](https://github.com/onfido/castor-icons/pull/143) should not be failing anymore.
N/A
=> ci: commitlint exclude dependabot (preview)

README.md
After GitHub introducing built-in index (table of content), our current heading included additional symbols resulting in odd appearance in UI:
Move "dot" alongside badge to a newline after the heading.
On https://github.com/onfido/castor-icons/tree/docs/better-gh-index
N/A
=> docs: clean heading for better index

README.md
New badge to indicate bundle size.
Use [bundlephobia](https://github.com/pastelsky/bundlephobia) to analyze and display minzipped size.
On https://github.com/onfido/castor-icons/tree/docs/bundle-size-badge
N/A
=> docs: add badge to indicate bundle size

.versionrc.json, package-lock.json, scripts/bump-package-lock.cjs
npm workspace version bump in `package-lock.json` requires version to be bumped in 2 places.
Bumping cannot be done by just specifying a file, instead a custom bumper has to be used, same as on https://github.com/onfido/castor/pull/234 and https://github.com/onfido/castor-tokens/pull/13.
`npm run release -- --dry-run`
N/A
=> build: correctly bump version in package-lock.json file

.github/workflows/lint.yml, package.json, tsconfig.generated.json, tsconfig.json
Following https://github.com/onfido/castor/pull/718, catch TS (type) errors ahead of time.
Run `tsc --noEmit` on lint.
Locally, on CI.
Had to ignore a lib check, otherwise no way to ignore `@types` from `node_modules`, where `svg-sprite` is failing:
=> build: lint ts

package-lock.json, package.json, scripts/build.ts
Following https://github.com/onfido/castor/pull/202, sorting imports automatically.
Sort with Prettier using `prettier-plugin-organize-imports`.
N/A
N/A
=> build: automatically sort imports

.github/workflows/lint.yml, .github/workflows/publish.yml
When upgrading Node version, we need to change it in multiple places. However, as we do use `.nvmrc` config, better to use such on CI also.
On CI, read Node version required from `.nvmrc` file, then use that when setting up Node.
On CI pipeline, inspecting what Node version was used.
N/A
=> ci: setup node version based on .nvmrc file

.github/workflows/lint.yml, .github/workflows/publish.yml
Speed up CI jobs by caching npm.
Follow Node's [npm approach](https://github.com/actions/cache/blob/main/examples.md#node---npm) to caching, using action.
N/A
N/A
=> ci: cache npm

.husky/prepare-commit-msg
Husky should run Commitizen via npx (not via Yarn).
Use npx to run Commitizen command.
Tested locally.
N/A
=> chore: run commitizen via npx

scripts/build.ts, tsconfig.generated.json
Use `index.ts` instead of `index.tsx` for main export + types.
Should fix https://github.com/onfido/castor-icons/issues/272.
Rename auto-generated `index.tsx` to `index.ts` during the build.
Also rename directory from `tsx` to just `ts`.
Tested locally.
N/A
=> build: rename ts index extension from *.tsx to *.ts

src/icons.json
Add `circle-three-quarter-solid`
Reuse from Boxicons
Preview icons page
None
=> feat: add circle-three-quarter-solid

.svgrrc.json, package.json, scripts/build.ts, tsconfig.json
Due to a bug in `svgr` it does not emit `import React` as it would be necessary for runtime execution of the components
Build with TypeScript's `react: "react-jsx"` new transform instead so necessary imports are correctly inserted
https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html
https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#jsx-factories
New components work in runtime, old ones didn't
Requires `react: >=17 || ^16.14 || ^15.7 || ^0.14.10` but previously we did not specify any necessary versions
=> fix: build with react-jsx

src/icons.json
New "plus-circle" icon.
Add "plus-circle" icon from Boxicons.
On preview.
N/A
=> feat: add plus-circle
