- .github/workflows/lint.yml
Running Prettier and ESLint [using Lint Actions](https://github.com/marketplace/actions/lint-action), then also running commitlint on a side.
> ci: run linters

- .github/workflows/build.yml
This tries to build the package on every commit push (as a test), excluding release branches as they already build the package for deployment (hence testing this).
> ci: build package (test)

- .github/PULL_REQUEST_TEMPLATE.md
Adds a (very simple) template for a pull request.
Probably last thing we need for the release.
Based on: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository
This closes issue #6.
> docs: pull request template

- package.json
- scripts/build.ts
For the 1st release some info should be added/edited on the `package.json` file.
- set description
- set homepage
- set/improve URLs for Git repository and bugs/issues
This closes issue #8.
Checking distribution generated `package.json` file:
N/A
> chore(package): improve package info

- .github/workflows/rebase.yml
Adding ability to rebase automatically.
Based on [GitHub action to automatically rebase PRs](https://github.com/cirrus-actions/rebase).
Will need to test on future PR, unfortunately.
N/A
> ci: automatic rebase

- src/icons.json
- src/svg/circle-solid.svg
New "circle-solid" icon.
Add "circle-solid" custom icon.
Build tested locally.
N/A
> feat: add circle-solid

- src/icons.json
Add `sync` icon.
Add boxicon svg path to json.
Locally.
None.
> feat: add sync icon

- scripts/build.ts
Include `CHANGELOG.md` in distributed package.
Add copying of `CHANGELOG.md` to distribution directory.
Locally checking `dist` directory.
N/A
> build: include changelog

- .github/workflows/lint.yml
- .lintstagedrc.json
- package.json
Make sure linting applies to all current and any future required files.
Align with https://github.com/onfido/castor/pull/112.
Locally, then on CI.
N/A
> build: align linting

- .github/workflows/lint.yml
- .lintstagedrc.json
- .stylelintrc.json
- package-lock.json
- package.json
Newly added example template has style that should be linted.
Using stylelint locally, upon commit, then on CI too.
Tested locally, CI can only be tested when merged.
N/A
> chore: lint style with stylelint

- src/icons.json
New "rotate-right" icon.
Add "rotate-right" icon.
On preview.
N/A
> feat: add rotate-right

- src/icons.json
New "pause" icon.
Add "pause" icon.
On preview.
N/A
> feat: add pause

- src/icons.json
New "grid" icon.
Add "grid" icon.
On preview.
N/A
> feat: add grid

- src/icons.json
New "refresh" icon.
Add "refresh" icon.
On preview.
N/A
> feat: add refresh

- src/icons.json
New "dots-horizontal-rounded" icon.
Add "dots-horizontal-rounded" icon from Boxicons.
On preview.
N/A
> feat: add dots-horizontal-rounded

- src/icons.json
New "grid-solid" icon.
Add "grid-solid" icon from Boxicons.
On preview.
N/A
> feat: add grid-solid

- src/icons.json
New "list-ul" icon.
Add "list-ul" icon from Boxicons.
On preview.
N/A
> feat: add list-ul

- .github/workflows/preview.yml
- .github/workflows/publish.yml
- CONTRIBUTING.md
Improve release process.
Move back from "tag" release process to "branch" one, then also include how to deal with version tags for latest versions.
With the next release probably.
N/A
> build: improve release process

- src/icons.json
- src/svg/flag.svg
New "flag" icon.
Add "flag" custom icon.
On preview.
N/A
> feat: add flag

- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
Add VS Code configuration.
Use same settings  as on Castor itself.
Checked locally on VS Code.
Only for contributors using VS Code.
> chore: add vscode config

- src/icons.json
New "dots-vertical-rounded" icon.
Add "dots-vertical-rounded" icon from Boxicons.
On preview.
N/A
> feat: add dots-vertical-rounded

- src/icons.json
- src/svg/sort-down.svg
- src/svg/sort-up.svg
New "sort-up" and "sort-down" icons.
Add "sort-up" and "sort-down" custom icons.
On preview.
N/A
> feat: add sort-up and sort-down

- src/icons.json
New "stopwatch" icon.
Add "stopwatch" icon from Boxicons.
On preview.
N/A
> feat: add stopwatch

- src/icons.json
New "folder" icon.
Add "folder" icon from Boxicons.
On preview.
N/A
> feat: add folder

- src/icons.json
- src/svg/skip-to-start.svg
New "skip-to-start" icon.
Add "skip-to-start" custom icon.
On preview.
N/A
> feat: add skip-to-start

- src/icons.json
- src/svg/skip-next.svg
- src/svg/skip-previous.svg
New "skip-previous" and "skip-next" icons.
Add "skip-previous" and "skip-next" custom icons.
On preview.
N/A
> feat: add skip-next and skip-previous

- src/icons.json
New "minus-circle" icon.
Add "minus-circle" icon from Boxicons.
On preview.
N/A
> feat: add minus-circle

- README.md
- templates/example.html
Adds `Powered by Vercel` logo as required for OSS sponsorship. 
N/A
N/A
N/A
> docs: add vercel logo

- templates/example.html
Current example does not fully validate: https://validator.w3.org/nu/?doc=https%3A%2F%2Fonfido.github.io%2Fcastor-icons%2F
Add section headings, alternative image text.
Example should validate: https://validator.w3.org/nu/?doc=https%3A%2F%2Fonfido-castor-icons-preview-pr-201.surge.sh%2F
N/A
> docs: validate example

- templates/example.html
Follow heading naming as in https://github.com/onfido/castor/pull/651.
Rename heading "support" to "sponsors".
On a preview, inspecting a heading.
N/A
> docs: rename "support" to "sponsors"

- src/icons.json
New "circle" icon.
Add "circle" icon from Boxicons.
On preview.
N/A
> feat: add circle

- src/icons.json
New "square" icon.
Add "square" icon from Boxicons.
On preview.
N/A
> feat: add square

- src/icons.json
New "shape-polygon" icon.
Add "shape-polygon" icon from Boxicons.
On preview.
N/A
> feat: add shape-polygon

- src/icons.json
- src/svg/exclamation.svg
New "exclamation" icons.
Add "exclamation" custom icons.
On preview.
N/A
> feat: add exclamation

- src/icons.json
New "move" icon.
Add "move" icon from Boxicons.
On preview.
N/A
> feat: add move

- src/icons.json
Add `crosshair` icon.
Use boxicons'.
Preview.
None.
> feat: add crosshair

- svgo.config.js
Prettier automatic write. Makes it easier to read I guess?
Run prettier.
> style: prettier on svgo.config

- CHANGELOG.md
- package-lock.json
- package.json
Merge release back in to main branch
> chore(release): 2.7.0

- package-lock.json
- templates/example.html
- tsconfig.json
- `npm audit fix`
- `tsconfig` enable strict
- `example.html` use rem instead of px
> chore: cleanup

- src/icons.json
New "upload" icon.
Add "upload" icon from Boxicons.
On preview.
N/A
> feat: add upload

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 2.8.0

- scripts/build.ts
Fix TypeScript compilation for users with factories other than `react-jsx`
Declare `React` as a local variable in each place where JSX is used
Castor linting passes, tested in an Onfido internal app too and it works as well
The workaround is quite inelegant, ideally TypeScript would be able to understand factory boundaries.
Without a proper solution migrating Castor itself to `react-jsx` sounds like a bad idea.
> fix: jsx factory types

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 2.8.2

- src/icons.json
New "video" icon.
Add "video" icon from Boxicons.
On preview.
N/A
> feat: add video

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 2.9.0

- src/icons.json
> feat: add calendar

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 2.10.0

- src/icons.json
Add the file-pdf icon.
Icon comes from boxicons
N/A
N/A
> feat: add file-pdf icon

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 2.12.0

- CHANGELOG.md
- package-lock.json
- package.json
Outline the change rationale (Why?)
Detail the approach (How?)
Describe the testing performed to verify the change. (or N/A)
Any significant risks, e.g. customer impact, backward compatibility, new tech debt. (or N/A)
> chore(release): 2.13.0

- src/icons.json
> feat: add bar-chart icon

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 2.15.0

- src/icons.json
New "help-circle" icon.
Add "help-circle" icon from Boxicons.
On preview.
N/A
> feat: add help-circle

- src/icons.json
New "transfer" icon.
Add "transfer" icon from Boxicons.
On preview.
N/A
> feat: add transfer

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 2.16.0

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 2.19.0

- .svgrrc.json
Outline the change rationale (Why?)
Detail the approach (How?)
Describe the testing performed to verify the change. (or N/A)
Any significant risks, e.g. customer impact, backward compatibility, new tech debt. (or N/A)
> feat: add data-castor-icon=true to all icons

- CHANGELOG.md
- package-lock.json
- package.json
Outline the change rationale (Why?)
Detail the approach (How?)
Describe the testing performed to verify the change. (or N/A)
Any significant risks, e.g. customer impact, backward compatibility, new tech debt. (or N/A)
> chore(release): 2.20.0

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 2.21.0

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 2.22.0

- CHANGELOG.md
- package-lock.json
- package.json
Outline the change rationale (Why?)
Detail the approach (How?)
Describe the testing performed to verify the change. (or N/A)
Any significant risks, e.g. customer impact, backward compatibility, new tech debt. (or N/A)
> chore(release): 2.23.1
